
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.util.Formatter;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author av
 */
public class CALC extends javax.swing.JFrame 
        implements KeyListener     {

    /**
     * Creates new form CALC
     */
    double fv=0.0;
    double cv=0.0;
    double lv=0.0;
    double rv=0.0;
    double cbwv,lbwv,xlv,xcv,fov,qlv,qcv=0.0;
    int c=0;
    int fbc,cbc,lbc=0;
    public CALC() {

        initComponents();
           f1.addKeyListener(this);  l1.addKeyListener(this);  r1.addKeyListener(this);  c1.addKeyListener(this);f2.addKeyListener(this);f3.addKeyListener(this);f4.addKeyListener(this);f5.addKeyListener(this);l2.addKeyListener(this);l3.addKeyListener(this);l4.addKeyListener(this);c2.addKeyListener(this);c3.addKeyListener(this);c4.addKeyListener(this);r2.addKeyListener(this);r2.addKeyListener(this);xl.addKeyListener(this);xc.addKeyListener(this);
            
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        f1 = new javax.swing.JTextField();
        l1 = new javax.swing.JTextField();
        c1 = new javax.swing.JTextField();
        r1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        f2 = new javax.swing.JRadioButton();
        f5 = new javax.swing.JRadioButton();
        f3 = new javax.swing.JRadioButton();
        f4 = new javax.swing.JRadioButton();
        l3 = new javax.swing.JRadioButton();
        l4 = new javax.swing.JRadioButton();
        l2 = new javax.swing.JRadioButton();
        c3 = new javax.swing.JRadioButton();
        c4 = new javax.swing.JRadioButton();
        c2 = new javax.swing.JRadioButton();
        r3 = new javax.swing.JRadioButton();
        r2 = new javax.swing.JRadioButton();
        xl = new javax.swing.JTextField();
        qc = new javax.swing.JTextField();
        ql = new javax.swing.JTextField();
        xc = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cbw = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lbw = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        f1.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        f1.setText("0.0");
        f1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f1ActionPerformed(evt);
            }
        });

        l1.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        l1.setText("0.0");
        l1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                l1ActionPerformed(evt);
            }
        });

        c1.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        c1.setText("0.0");
        c1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c1ActionPerformed(evt);
            }
        });

        r1.setText("0.0");
        r1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        jLabel1.setText("R");

        jLabel2.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        jLabel2.setText("FREQ");

        jLabel3.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        jLabel3.setText("L");

        jLabel4.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        jLabel4.setText("C");

        buttonGroup1.add(f2);
        f2.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        f2.setText("HZ");
        f2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f2ActionPerformed(evt);
            }
        });

        buttonGroup1.add(f5);
        f5.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        f5.setText("GZ");
        f5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f5ActionPerformed(evt);
            }
        });

        buttonGroup1.add(f3);
        f3.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        f3.setText("KZ");
        f3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f3ActionPerformed(evt);
            }
        });

        buttonGroup1.add(f4);
        f4.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        f4.setSelected(true);
        f4.setText("MZ");
        f4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f4ActionPerformed(evt);
            }
        });

        buttonGroup2.add(l3);
        l3.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        l3.setText("uH");
        l3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                l3ActionPerformed(evt);
            }
        });

        buttonGroup2.add(l4);
        l4.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        l4.setText("nH");
        l4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                l4ActionPerformed(evt);
            }
        });

        buttonGroup2.add(l2);
        l2.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        l2.setSelected(true);
        l2.setText("mH");
        l2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                l2ActionPerformed(evt);
            }
        });

        buttonGroup3.add(c3);
        c3.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        c3.setText("nF");
        c3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c3ActionPerformed(evt);
            }
        });

        buttonGroup3.add(c4);
        c4.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        c4.setText("pF");
        c4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c4ActionPerformed(evt);
            }
        });

        buttonGroup3.add(c2);
        c2.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        c2.setSelected(true);
        c2.setText("uF");
        c2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c2ActionPerformed(evt);
            }
        });

        buttonGroup4.add(r3);
        r3.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        r3.setText("K OHM");
        r3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r3ActionPerformed(evt);
            }
        });

        buttonGroup4.add(r2);
        r2.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        r2.setSelected(true);
        r2.setText("OHM");
        r2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r2ActionPerformed(evt);
            }
        });

        xl.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        xl.setText("0.0");
        xl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xlActionPerformed(evt);
            }
        });

        qc.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        qc.setText("0.0");
        qc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qcActionPerformed(evt);
            }
        });

        ql.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        ql.setText("0.0");
        ql.setToolTipText("");
        ql.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qlActionPerformed(evt);
            }
        });

        xc.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        xc.setText("0.0");
        xc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xcActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        jLabel5.setText("QL");

        jLabel6.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        jLabel6.setText("QC");

        jLabel7.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        jLabel7.setText("XL");

        jLabel8.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        jLabel8.setText("XC");

        jLabel9.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        jLabel9.setText("BW-C");

        cbw.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        cbw.setText("0.0");

        jLabel10.setFont(new java.awt.Font("Noto Sans", 1, 24)); // NOI18N
        jLabel10.setText("SELCT UNITS BEFORE DATA ");

        jLabel11.setFont(new java.awt.Font("Noto Sans", 1, 24)); // NOI18N
        jLabel11.setText("DEL=CLEAR;  ENTR=CALC");

        jLabel12.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        jLabel12.setText("BW-L");

        lbw.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        lbw.setText("0.0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(475, 475, 475))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(117, 117, 117))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(c1)
                                    .addComponent(f1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(r1)
                                    .addComponent(l1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(62, 62, 62)
                                        .addComponent(f3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(f4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(f5))
                                    .addComponent(f2)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(l2)
                                                .addGap(18, 18, 18)
                                                .addComponent(l3)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(l4))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(c2)
                                                    .addComponent(r2))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(r3)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(c3)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(c4)))))
                                        .addGap(77, 77, 77)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel6)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(qc))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel5)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(ql, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jLabel7)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel8)
                                                .addGap(11, 11, 11)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(xl)
                                            .addComponent(xc, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel9)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(cbw))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel12)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(lbw, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(f1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(f2)
                            .addComponent(f3)
                            .addComponent(f4)
                            .addComponent(f5))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lbw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(xl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(xc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(13, 13, 13)
                                    .addComponent(l1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(c1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(c2)
                                        .addComponent(c3)
                                        .addComponent(c4)))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(ql, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(qc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(r1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(r2)
                                .addComponent(r3))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(l2)
                            .addComponent(l3)
                            .addComponent(l4))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void f1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_f1ActionPerformed

    private void r1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r1ActionPerformed

    private void f2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f2ActionPerformed
        // TODO add your handling code here:
      
        
    }//GEN-LAST:event_f2ActionPerformed

    private void f5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_f5ActionPerformed

    private void f3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_f3ActionPerformed

    private void f4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_f4ActionPerformed

    private void l3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_l3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_l3ActionPerformed

    private void l4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_l4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_l4ActionPerformed

    private void l2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_l2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_l2ActionPerformed

    private void c3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c3ActionPerformed

    private void c4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c4ActionPerformed

    private void c2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c2ActionPerformed

    private void r3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r3ActionPerformed

    private void r2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r2ActionPerformed

    private void qlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qlActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_qlActionPerformed

    private void qcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_qcActionPerformed

    private void xlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xlActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_xlActionPerformed

    private void xcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_xcActionPerformed

    private void l1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_l1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_l1ActionPerformed

    private void c1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c1ActionPerformed
    

    
    /**0.0
     * @param args the command line arguments
     */
    public static void main(String args[]) {
   
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CALC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CALC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CALC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CALC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
             
                new CALC().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JTextField c1;
    private javax.swing.JRadioButton c2;
    private javax.swing.JRadioButton c3;
    private javax.swing.JRadioButton c4;
    private javax.swing.JTextField cbw;
    private javax.swing.JTextField f1;
    private javax.swing.JRadioButton f2;
    private javax.swing.JRadioButton f3;
    private javax.swing.JRadioButton f4;
    private javax.swing.JRadioButton f5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField l1;
    private javax.swing.JRadioButton l2;
    private javax.swing.JRadioButton l3;
    private javax.swing.JRadioButton l4;
    private javax.swing.JTextField lbw;
    private javax.swing.JTextField qc;
    private javax.swing.JTextField ql;
    private javax.swing.JTextField r1;
    private javax.swing.JRadioButton r2;
    private javax.swing.JRadioButton r3;
    private javax.swing.JTextField xc;
    private javax.swing.JTextField xl;
    // End of variables declaration//GEN-END:variables

    @Override
    public void keyPressed(KeyEvent e) {
     //   throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
     if(e.getKeyCode()==KeyEvent.VK_ENTER){ 
         c++;
         if(c<2){
     int fy,ly,cy=0;
         //   double ocv,ofv,olv=0;
             fv=Double.parseDouble(f1.getText());
             cv=Double.parseDouble(c1.getText());
             lv=Double.parseDouble(l1.getText());
     //        rv=Double.parseDouble(r1.getText());
            final double rv=0.1;
           //  ocv=cv;
             //ofv=fv;
             //olv=lv;
                     
            if(fv>0){
            fy=1;
            }else{
                fy=0;
            }
     
              if(cv>0){
             cy=1;
            }else{
                cy=0;
            }
                if(lv>0){
             ly=1;
            }else{
                ly=0;
                
                
                
                
                
                
            }
                        if(rv>0){
            int ry=1;
            }else{
              int  ry=0;
            }
                    if(f2.isSelected()){
                        fv=fv*1;fbc=2;
                    }
                        if(f3.isSelected()){
                            fv=fv*1000;fbc=3;
                            
                        }
                        if(f4.isSelected()){
                            fv=fv*Math.pow(10,6);fbc=4;
                        }
                        if(f5.isSelected()){
                            fv=fv*Math.pow(10, 9);fbc=5;
                        }
                      if(l2.isSelected()){
                          lv=lv*Math.pow(10,-3);lbc=2;
                      }
                        if(l3.isSelected()){
                            lv=lv*Math.pow(10,-6);lbc=3;
                            
                        }
                        if(l4.isSelected()){
                            lv=lv*Math.pow(10, -9);lbc=4;
                        }
                       if(c2.isSelected()){
                           cv=cv*Math.pow(10,-6);cbc=2;
                       }
                        
                        if(c3.isSelected()){
                            cv=cv*Math.pow(10,-9);cbc=3;
                            
                        }
                        if(c4.isSelected()){
                            cv=cv*Math.pow(10, -12);cbc=4;
                        }
                       
                        if(r3.isSelected()){
                            //rv=rv*1000;c=0;
                            //
                        }
                       
                if(fy==1&&cy==1){
            lv=1/(4*3.14*3.14*fv*fv*cv);
            double olv=lv;
    //      JOptionPane.showMessageDialog(this," "+lv);
           if(l2.isSelected()){
                lv=lv*1000;
            }
             if(l3.isSelected()){
                lv=lv*1000000;
            } if(l4.isSelected()){
                lv=lv*Math.pow(10,9);
            }
               //double rlv=Math.round(lv*1000.0)/100.0;
               
                
         //      l1.setText(""+lv);
           // fov=1/(2*3.14*(Math.sqrt((lv*cv))));
          //  fov=Math.round(fov*100)/100;
            xcv=1/(2*3.14*fv*cv);
          //  xcv=Math.round(xcv*100)/100;
            xlv=2*3.14*fv*olv;
           qlv=xlv/rv;
           qcv=xcv/rv;
            lbwv=fv/qlv;
           cbwv=fv/qcv;
             Formatter cbfmt=new Formatter();
             cbfmt.format("%16.2e",cbwv);
             Formatter lbfmt=new Formatter();
             lbfmt.format("%16.2e",lbwv);
            Formatter cfmt=new Formatter();
             cfmt.format("%16.2e",xcv);
                Formatter lfmt=new Formatter();
             lfmt.format("%16.2e",xlv);
             Formatter qcfmt=new Formatter();
             cfmt.format("%16.2e",qcv);
             Formatter qlfmt=new Formatter();
             cfmt.format("%16.2e",qlv);
          //  xlv=Math.round(lv*100)/100;
          //  String slv=Double.toString(lv);
              //  String rkv = String.format("%.2e", slv);
           Formatter   fmt=new Formatter();
           fmt.format("%16.2e",lv);
          xl.setText(""+lfmt);
            xc.setText(""+cfmt);l1.setText(""+fmt);
              ql.setText(""+qlfmt);
            qc.setText(""+qcfmt);
             lbw.setText(""+lbfmt);
            cbw.setText(""+cbfmt);
                       //JOptionPane.showMessageDialog(this,""+fmt);
                }   
                if(fy==1&&ly==1){
                             cv=1/(4*3.14*3.14*fv*fv*lv);
                             double ocv=cv;
                             if(c2.isSelected()){
                                 cv=cv/Math.pow(10,-6);cbc=2;
                                 
                             }if(c3.isSelected()){
                                 cv=cv/Math.pow(10,-9);cbc=3;
                             }if(c4.isSelected()){
                                 cv=cv/Math.pow(10,-12);cbc=4;
                             }
                              // fov=1/(2*3.14*(Math.sqrt((lv*cv))));
                            
          //  fov=Math.round(fov*100)/100;
            xcv=1/(2*3.14*fv*ocv);
          //  xcv=Math.round(xcv*100)/100;
            xlv=2*3.14*fv*lv;
            qlv=xlv/rv;
           qcv=xcv/rv;
           lbwv=fv/qlv;
           cbwv=fv/qcv;
           Formatter cbfmt=new Formatter();
             cbfmt.format("%16.2e",cbwv);
             Formatter lbfmt=new Formatter();
             lbfmt.format("%16.2e",lbwv);
           Formatter qcfmt=new Formatter();
             qcfmt.format("%16.2e",qcv);
             Formatter qlfmt=new Formatter();
             qlfmt.format("%16.2e",qlv);
           Formatter cfmt=new Formatter();
             cfmt.format("%16.2e",xcv);
                Formatter lfmt=new Formatter();
             lfmt.format("%16.2e",xlv);
          xl.setText(""+lfmt);
            xc.setText(""+cfmt);
              Formatter   fmt=new Formatter();
           fmt.format("%16.2e",cv);
         //      cv=Math.round(cv*100)/100;
            c1.setText(""+fmt);
              ql.setText(""+qlfmt);
            qc.setText(""+qcfmt);
             lbw.setText(""+lbfmt);
            cbw.setText(""+cbfmt);
                   //    JOptionPane.showMessageDialog(this, ""+fy);
} 
             if(cy==1&&ly==1){
                    fov=1/(2*3.14*(Math.sqrt((lv*cv))));
                    double ofov=fov;
                    if(f2.isSelected()){
                        fov=fov*1;fbc=0;
                    }
                    if(f3.isSelected()){
                        fov=fov/1000;fbc=3;
                    }if(f4.isSelected()){
                        fov=fov/Math.pow(10,6);fbc=4;
                    }if(f5.isSelected()){
                        fov=fov/Math.pow(10,9);fbc=5;
                    }
                //     fov=Math.round(fov*100)/100;
         
            xcv=1/(2*3.14*ofov*cv);
            //cv=Math.round(xcv*100)/100;
            xlv=2*3.14*ofov*lv;
            //xlv=Math.round(lv*100)/100;
                   qlv=xlv/rv;
           qcv=xcv/rv;
            lbwv=ofov/qlv;
           cbwv=ofov/qcv;
           Formatter cbfmt=new Formatter();
             cbfmt.format("%16.2e",cbwv);
             Formatter lbfmt=new Formatter();
             lbfmt.format("%16.2e",lbwv);
            Formatter qcfmt=new Formatter();
             qcfmt.format("%16.2e",qcv);
               Formatter qlfmt=new Formatter();
             qlfmt.format("%16.2e",qlv);
                Formatter lfmt=new Formatter();
             lfmt.format("%16.2e",xlv);
             Formatter cfmt=new Formatter();
             cfmt.format("%16.2e",xcv);
          xl.setText(""+lfmt);
            Formatter   fmt=new Formatter();
           fmt.format("%16.2e",fov);
            xc.setText(""+cfmt);f1.setText(""+fmt);
            ql.setText(""+qlfmt);
            qc.setText(""+qcfmt);
            lbw.setText(""+lbfmt);
            cbw.setText(""+cbfmt);
                     //  JOptionPane.showMessageDialog(this, ""+cv);}
                
}else{
                 c=0;
             }
}else{


}

}else{
         
     }
     
}
    @Override
    public void keyTyped(KeyEvent e) {
      //  throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
       
                             
    }

    @Override
    public void keyReleased(KeyEvent e) {
     //   throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
      if(e.getKeyCode()==KeyEvent.VK_DELETE){
    c=0;
        fv=0.0;
        lv=0.0;
        cv=0.0;
        xcv=0.0;
        xlv=0.0;
        f1.setText("0.0");
        l1.setText("0.0");c1.setText("0.0");r1.setText("0.0");xl.setText("0.0");xc.setText("0.0");
        f4.setSelected(true);
        c2.setSelected(true);
        l2.setSelected(true);
        r2.setSelected(true);
    }
    }

}
